site_name: Tube Archivist Documentation
site_url: https://docs.tubearchivist.com
nav:
    - Home: 'index.md'
    - User Guide:
        - 'FAQ': 'faq.md'
        - 'Downloads Page': 'downloads.md'
        - 'Channels Pages': 'channels.md'
        - 'Video': 'video.md'
        - 'Playlists Pages': 'playlists.md'
        - 'Search': 'search.md'
        - 'Users': 'users.md'
        - 'Settings': 'settings.md'
    - Installation:
        - 'Docker-Compose (default)': 'installation/docker-compose.md'    
        - 'Unraid': 'installation/unraid.md'
        - 'Synology': 'installation/synology.md'
        - 'Podman': 'installation/podman.md'
        - 'Truenas Scale': 'installation/truenas-scale.md'
        - 'Helm Charts': 'installation/helm-charts.md'
    - Configuration:        
        - 'LDAP Authentication': 'configuration/ldap.md'          
        - 'Cast Support': 'configuration/cast.md' 
    - Links:
        - 'Main site': https://www.tubearchivist.com
        - 'Join us on Discord!': https://www.tubearchivist.com/discord
        - 'License': https://github.com/tubearchivist/tubearchivist/blob/master/LICENSE
        - 'Release Notes': https://github.com/tubearchivist/tubearchivist/releases
repo_url: https://github.com/tubearchivist/docs
markdown_extensions:
    - toc:
        permalink: "#"
    - admonition
    - pymdownx.details
    - pymdownx.superfences
theme:
  name: material
  logo: assets/logo-dark.jpg
  favicon: assets/favicon.ico
  font: false
  custom_dir: overrides
  palette:
    scheme: tubearchivist
  features:
    - navigation.footer
extra_css:
  - stylesheets/style.css
extra:
  analytics:
    provider: custom
plugins:
  - social:
      cards_color:
        fill: "#00202f" 
        text: "#eeeeee"
        cards_font: Sen-Bold
